# This is a basic workflow to help you get started with Actions

name: Daily Scrape

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
    - name: Checkout script repo
      uses: actions/checkout@v2
      
    - name: Checkout data repo
      uses: actions/checkout@v2
      with:
        repository: catskillpreservation/P-15056-000-comments
        token: ${{ secrets.DEPLOY_TOKEN }}
        path: comments
        
      
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests 
        
    - name: Prepare Selenium
      uses: nanasess/setup-chromedriver@master
      
    - name: Launch browser
      run: |
        google-chrome --version
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
   
    - name: Run
      run: python main.py --headless true
      
    - name: Commit files
      run: |
        cd comments
        git config user.name sommea
        git config user.email asommer999@gmail.com
        git add .
        git commit -m "Automated daily commit"
        git push
